version: '3.1'


volumes:
  web-insights-database:
    driver: local

services:
  web-insights-database:
    container_name: web-insights-database
    image: postgres
    volumes:
      - web-insights-database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: insider
      POSTGRES_USER: insider
      POSTGRES_DB: web_insights
    ports:
      - "5432:5432"
  web-insights-keycloak:
    command: start-dev
    container_name: web-insights-keycloak
    environment:
      KEYCLOAK_ADMIN: keycloak_admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - "8888:8080"