name: eslint

on:
  pull_request:
    paths:
      - '**/*.tsx'
      - '**/*.ts'
    branches:
      - main

env:
  NODE_VERSION: 18

defaults:
  run:
    working-directory: ./web-insights-app

jobs:
  linting:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Code Linting
        run: npm run eslint
