name: spring test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3

      - name: Start containers
        run: ./gradlew composeUp

      - name: Run tests
        run: ./gradlew test

      - name: Stop database containers
        if: always()
        run: ./gradlew composeDown