name: spring test

on:
  pull_request:
    branches:
      - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Start containers
        run: ./gradlew composeUp

      - name: Stop database containers
        if: always()
        run: ./gradlew composeDown