name: stylelint

on:
  pull_request:
    paths:
      - '**/*.css'
    branches:
      - main

env:
  NODE_VERSION: 18

defaults:
  run:
    working-directory: ./web-insights-web

jobs:
  linting:
    name: stylelint
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Style Linting
        run: npm run stylelint